spring.application.name=bankingapp


# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bankingapp
spring.datasource.username=root
spring.datasource.password=Nihal@1461
# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




# Port
server.port=8080